# Generated by Django 4.0.4 on 2022-07-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
