# Generated by Django 4.0.4 on 2022-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUs_img', models.CharField(max_length=50)),
                ('AboutUs_small_title', models.CharField(max_length=50)),
                ('AboutUs_title', models.CharField(max_length=50)),
                ('AboutUs_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
