# Generated by Django 4.0.4 on 2022-07-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
